logLevel: info

api: yes

hls: yes
hlsVariant: lowLatency

webrtc: yes

paths:
  all:
    source: publisher
    runOnReady: python /hooks/stream_event_hook.py stream_started $MTX_PATH
    runOnNotReady: python /hooks/stream_event_hook.py stream_ended $MTX_PATH
